version: 2

multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles

updates:
  - package-ecosystem: pip
    directory: /
    cooldown:
      default-days: 7
    patterns: ["*"]
    multi-ecosystem-group: weekly-dependencies

  - package-ecosystem: bundler
    directory: /
    cooldown:
      default-days: 7
    patterns: ["*"]
    multi-ecosystem-group: weekly-dependencies

  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    patterns: ["*"]
    multi-ecosystem-group: weekly-dependencies

  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 7
    patterns: ["*"]
    multi-ecosystem-group: weekly-dependencies
