export const TempoStreamChannelABI = [
	{
		type: 'constructor',
		inputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'CLOSE_GRACE_PERIOD',
		inputs: [],
		outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'VOUCHER_TYPEHASH',
		inputs: [],
		outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'channels',
		inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		outputs: [
			{ name: 'payer', type: 'address', internalType: 'address' },
			{ name: 'payee', type: 'address', internalType: 'address' },
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'deposit', type: 'uint128', internalType: 'uint128' },
			{ name: 'settled', type: 'uint128', internalType: 'uint128' },
			{ name: 'expiry', type: 'uint64', internalType: 'uint64' },
			{ name: 'closeRequestedAt', type: 'uint64', internalType: 'uint64' },
			{ name: 'finalized', type: 'bool', internalType: 'bool' },
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'computeChannelId',
		inputs: [
			{ name: 'payer', type: 'address', internalType: 'address' },
			{ name: 'payee', type: 'address', internalType: 'address' },
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'deposit', type: 'uint128', internalType: 'uint128' },
			{ name: 'expiry', type: 'uint64', internalType: 'uint64' },
			{ name: 'salt', type: 'bytes32', internalType: 'bytes32' },
		],
		outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'domainSeparator',
		inputs: [],
		outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getChannel',
		inputs: [{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' }],
		outputs: [
			{
				name: '',
				type: 'tuple',
				internalType: 'struct TempoStreamChannel.Channel',
				components: [
					{ name: 'payer', type: 'address', internalType: 'address' },
					{ name: 'payee', type: 'address', internalType: 'address' },
					{ name: 'token', type: 'address', internalType: 'address' },
					{ name: 'deposit', type: 'uint128', internalType: 'uint128' },
					{ name: 'settled', type: 'uint128', internalType: 'uint128' },
					{ name: 'expiry', type: 'uint64', internalType: 'uint64' },
					{ name: 'closeRequestedAt', type: 'uint64', internalType: 'uint64' },
					{ name: 'finalized', type: 'bool', internalType: 'bool' },
				],
			},
		],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'getVoucherDigest',
		inputs: [
			{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'cumulativeAmount', type: 'uint128', internalType: 'uint128' },
			{ name: 'validUntil', type: 'uint64', internalType: 'uint64' },
		],
		outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'view',
	},
	{
		type: 'function',
		name: 'open',
		inputs: [
			{ name: 'payee', type: 'address', internalType: 'address' },
			{ name: 'token', type: 'address', internalType: 'address' },
			{ name: 'deposit', type: 'uint128', internalType: 'uint128' },
			{ name: 'expiry', type: 'uint64', internalType: 'uint64' },
			{ name: 'salt', type: 'bytes32', internalType: 'bytes32' },
		],
		outputs: [{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' }],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'requestClose',
		inputs: [{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'settle',
		inputs: [
			{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'cumulativeAmount', type: 'uint128', internalType: 'uint128' },
			{ name: 'validUntil', type: 'uint64', internalType: 'uint64' },
			{ name: 'signature', type: 'bytes', internalType: 'bytes' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'topUp',
		inputs: [
			{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' },
			{ name: 'additionalDeposit', type: 'uint128', internalType: 'uint128' },
			{ name: 'newExpiry', type: 'uint64', internalType: 'uint64' },
		],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'function',
		name: 'withdraw',
		inputs: [{ name: 'channelId', type: 'bytes32', internalType: 'bytes32' }],
		outputs: [],
		stateMutability: 'nonpayable',
	},
	{
		type: 'event',
		name: 'ChannelOpened',
		inputs: [
			{ name: 'channelId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
			{ name: 'payer', type: 'address', indexed: true, internalType: 'address' },
			{ name: 'payee', type: 'address', indexed: true, internalType: 'address' },
			{ name: 'token', type: 'address', indexed: false, internalType: 'address' },
			{ name: 'deposit', type: 'uint256', indexed: false, internalType: 'uint256' },
			{ name: 'expiry', type: 'uint256', indexed: false, internalType: 'uint256' },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'CloseRequested',
		inputs: [
			{ name: 'channelId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
			{ name: 'closeGraceEnd', type: 'uint256', indexed: false, internalType: 'uint256' },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Settled',
		inputs: [
			{ name: 'channelId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
			{ name: 'cumulativeAmount', type: 'uint256', indexed: false, internalType: 'uint256' },
			{ name: 'deltaPaid', type: 'uint256', indexed: false, internalType: 'uint256' },
			{ name: 'newSettled', type: 'uint256', indexed: false, internalType: 'uint256' },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'TopUp',
		inputs: [
			{ name: 'channelId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
			{ name: 'additionalDeposit', type: 'uint256', indexed: false, internalType: 'uint256' },
			{ name: 'newDeposit', type: 'uint256', indexed: false, internalType: 'uint256' },
			{ name: 'newExpiry', type: 'uint256', indexed: false, internalType: 'uint256' },
		],
		anonymous: false,
	},
	{
		type: 'event',
		name: 'Withdrawn',
		inputs: [
			{ name: 'channelId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
			{ name: 'refunded', type: 'uint256', indexed: false, internalType: 'uint256' },
		],
		anonymous: false,
	},
	{ type: 'error', name: 'AmountExceedsDeposit', inputs: [] },
	{ type: 'error', name: 'AmountNotIncreasing', inputs: [] },
	{ type: 'error', name: 'ChannelAlreadyExists', inputs: [] },
	{ type: 'error', name: 'ChannelExpired', inputs: [] },
	{ type: 'error', name: 'ChannelFinalized', inputs: [] },
	{ type: 'error', name: 'ChannelNotExpired', inputs: [] },
	{ type: 'error', name: 'ChannelNotFound', inputs: [] },
	{ type: 'error', name: 'CloseNotRequested', inputs: [] },
	{ type: 'error', name: 'ECDSAInvalidSignature', inputs: [] },
	{
		type: 'error',
		name: 'ECDSAInvalidSignatureLength',
		inputs: [{ name: 'length', type: 'uint256', internalType: 'uint256' }],
	},
	{
		type: 'error',
		name: 'ECDSAInvalidSignatureS',
		inputs: [{ name: 's', type: 'bytes32', internalType: 'bytes32' }],
	},
	{ type: 'error', name: 'InvalidSignature', inputs: [] },
	{ type: 'error', name: 'NotPayer', inputs: [] },
	{ type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
	{ type: 'error', name: 'TransferFailed', inputs: [] },
	{ type: 'error', name: 'VoucherExpired', inputs: [] },
] as const
