import { describe, expect, it } from 'vitest'
import { recoverVoucherSigner, verifyVoucher } from './voucher'
import type { SignedVoucher } from './types'

/**
 * Cross-language voucher verification test.
 *
 * This test verifies that vouchers signed by Python (presto) can be verified
 * by TypeScript (ai-payments). The test data is generated by running:
 *   python scripts/test_cross_lang_voucher.py
 *
 * The signature was generated using the foundry test account:
 *   Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
 *   Address: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
 */
describe('Cross-language voucher verification', () => {
	const TEST_ESCROW = '0x5513B62Ec86A8354D03E1dc5378886cdc2dD6A09'
	const TEST_CHAIN_ID = 42431
	const TEST_SIGNER = '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'

	// Voucher signed by Python presto using the above private key
	const pythonSignedVoucher: SignedVoucher = {
		channelId: '0x2a953fdfcb3e13597b6831a2cbc07dc6323a502c5dad037183358876e3838c76',
		cumulativeAmount: 100000n,
		validUntil: 9999999999n,
		signature:
			'0x4a256bf891f48d159674f18d868a57c2796683fa95ba4486e3a1ccbefeaf4f5661906e481b8c08cb0d45925dbc008ba63a33af10bdad2563ca286bf84262187c1b',
	}

	it('should recover correct signer from Python-generated voucher', async () => {
		const signer = await recoverVoucherSigner(TEST_ESCROW, TEST_CHAIN_ID, pythonSignedVoucher)
		expect(signer.toLowerCase()).toBe(TEST_SIGNER.toLowerCase())
	})

	it('should verify Python-generated voucher against expected signer', async () => {
		const isValid = await verifyVoucher(
			TEST_ESCROW,
			TEST_CHAIN_ID,
			pythonSignedVoucher,
			TEST_SIGNER,
		)
		expect(isValid).toBe(true)
	})

	it('should reject Python-generated voucher with wrong signer', async () => {
		const wrongSigner = '0x0000000000000000000000000000000000000001'
		const isValid = await verifyVoucher(
			TEST_ESCROW,
			TEST_CHAIN_ID,
			pythonSignedVoucher,
			wrongSigner,
		)
		expect(isValid).toBe(false)
	})
})
